# Generated by Django 6.0.4 on 2026-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('surnames', models.CharField(max_length=30)),
                ('client_id', models.IntegerField()),
                ('dat_ini', models.DateField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
